---
- name: uninstall_httpd_playbook
  hosts: linux_web_hosts
  remote_user: root
  become: true
  tasks:
          - name: uninstall httpd
            yum:
                  name: httpd
                  state: absent

          - name: start firewalld
            service:
                    name: firewalld
                    state: started
                    enabled: yes
